/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package privacy;

/**
 *
 * @author Abdulrahman_69
 */
public class PrivacyAttacker extends javax.swing.JFrame {

    /**
     * Creates new form PrivacyAttacker
     */
    public PrivacyAttacker() {
        initComponents();
        HomeLat.setText(""+Home.new_info.home.Lng);
        HomeLng.setText(""+Home.new_info.home.Lat);
        WorkLat.setText(""+Home.new_info.work.Lng);
        WorkLng.setText(""+Home.new_info.work.Lat);
        MVPlat.setText(""+Home.new_info.mvp.Lng);
        MVPlng.setText(""+Home.new_info.mvp.Lat);
        WPlat.setText(""+Home.new_info.wp.Lng);
        WPlng.setText(""+Home.new_info.wp.Lat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labIntroduction = new javax.swing.JLabel();
        labHomeAddress = new javax.swing.JLabel();
        labWorkAddress = new javax.swing.JLabel();
        labMostVisit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        butVisiualization = new javax.swing.JButton();
        butBack = new javax.swing.JButton();
        butPlaces = new javax.swing.JButton();
        labPlaces = new javax.swing.JLabel();
        butVisiualize = new javax.swing.JLabel();
        HomeLat = new javax.swing.JLabel();
        HomeLng = new javax.swing.JLabel();
        WorkLat = new javax.swing.JLabel();
        WorkLng = new javax.swing.JLabel();
        MVPlat = new javax.swing.JLabel();
        MVPlng = new javax.swing.JLabel();
        WPlat = new javax.swing.JLabel();
        WPlng = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labIntroduction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labIntroduction.setForeground(new java.awt.Color(204, 0, 51));
        labIntroduction.setText("These are the information that we know about you ");

        labHomeAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labHomeAddress.setText(" Home : ");

        labWorkAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labWorkAddress.setText(" Work  :");

        labMostVisit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labMostVisit.setText("Most Visitied Places :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Weekend Places :");

        butVisiualization.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        butVisiualization.setText("Visiualization ");
        butVisiualization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVisiualizationActionPerformed(evt);
            }
        });

        butBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        butBack.setText("Back ");
        butBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBackActionPerformed(evt);
            }
        });

        butPlaces.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        butPlaces.setText("Places");
        butPlaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPlacesActionPerformed(evt);
            }
        });

        labPlaces.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labPlaces.setText("To see places near to you");

        butVisiualize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        butVisiualize.setText("To visiaulize you profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(butBack, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(HomeLat, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                            .addComponent(HomeLng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(WorkLat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(WorkLng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(butPlaces, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labPlaces))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(MVPlng, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                            .addComponent(MVPlat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(293, 293, 293))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(butVisiualize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(butVisiualization, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(159, 159, 159))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labHomeAddress)
                                .addGap(75, 75, 75)
                                .addComponent(labWorkAddress)
                                .addGap(109, 109, 109)
                                .addComponent(labMostVisit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(WPlng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(WPlat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(labIntroduction)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labIntroduction)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labMostVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HomeLat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WorkLat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HomeLng, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(WorkLng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MVPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MVPlng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WPlng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(butVisiualize)
                        .addGap(18, 18, 18)
                        .addComponent(butVisiualization)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butBack)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labPlaces)
                        .addGap(18, 18, 18)
                        .addComponent(butPlaces)
                        .addGap(175, 175, 175))))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-796)/2, (screenSize.height-618)/2, 796, 618);
    }// </editor-fold>//GEN-END:initComponents

    private void butVisiualizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVisiualizationActionPerformed

       Visiualization go = new Visiualization();
       go .setVisible(true);
       super.dispose();
    }//GEN-LAST:event_butVisiualizationActionPerformed

    private void butBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBackActionPerformed
       
       UserInfo go = new UserInfo();
       go.setVisible(true);
       super.dispose();
    }//GEN-LAST:event_butBackActionPerformed

    private void butPlacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPlacesActionPerformed
        Places go = new Places();
        go.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_butPlacesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrivacyAttacker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrivacyAttacker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrivacyAttacker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrivacyAttacker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PrivacyAttacker().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomeLat;
    private javax.swing.JLabel HomeLng;
    private javax.swing.JLabel MVPlat;
    private javax.swing.JLabel MVPlng;
    private javax.swing.JLabel WPlat;
    private javax.swing.JLabel WPlng;
    private javax.swing.JLabel WorkLat;
    private javax.swing.JLabel WorkLng;
    private javax.swing.JButton butBack;
    private javax.swing.JButton butPlaces;
    private javax.swing.JButton butVisiualization;
    private javax.swing.JLabel butVisiualize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labHomeAddress;
    private javax.swing.JLabel labIntroduction;
    private javax.swing.JLabel labMostVisit;
    private javax.swing.JLabel labPlaces;
    private javax.swing.JLabel labWorkAddress;
    // End of variables declaration//GEN-END:variables
}
